### ISSUE TITLE
Missing python dependencies

### ISSUE THREAD

**Issue by davidyoung8906** [Rhapsod/sapienz#11]
When running sapienz against an open-source app, it throws the following errors:

```
Traceback (most recent call last):
  File "main.py", line 18, in <module>
    from plot import two_d_line
  File "/home/vagrant/issta16_artefact/plot/two_d_line.py", line 6, in <module>
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 115, in <module>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup
    globals(),locals(),[backend_name],0)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 6, in <module>
    from six.moves import tkinter as Tk
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 203, in load_module
    mod = mod._resolve()
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 115, in _resolve
    return _import_module(self.mod)
  File "/usr/local/lib/python2.7/dist-packages/six.py", line 82, in _import_module
    __import__(name)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 42, in <module>
    raise ImportError, str(msg) + ', please install the python-tk package'
ImportError: No module named _tkinter, please install the python-tk package

```
Can you let me know how to resolve this issue?

Thanks!

**Comment by lucaspelloni2** [comment]
It seems that you have not installed all the required python dependencies. I had the same problem!
I solved this issue in the following way: 

- If you have brew installed run this command line again: **$ brew install python**. After that, run again **sudo pip install -r requirements.txt**. 
- If this doesn't work for you, download **Anaconda** and set its python as the "default" python for your Mac (http://stackoverflow.com/questions/39438049/how-to-set-the-default-python-path-for-anaconda). Once installed, run again **sudo pip install -r requirements.txt**.

Hope it helps!

**Comment by chinh-tran** [comment]
You need the python-tk package: **sudo apt-get install python-tk**
