### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by filipemfg** [Rhapsod/sapienz#14]
Hello,

I'm trying to run Sapienz on Ubuntu 16.04 and using the aard2 as software under test (https://github.com/itkach/aard2-android/releases)

I made all the configurations showed in the tutorial, but when I try to run the Sapienz, this message is displayed:

=================

Running on Linux
/bin/sh: 1: aapt: not found
mkdir: it is impossible to create directory “.../aard2-android-0.38.apk_output”: File or directory not found

### Working on apk: 
Preparing devices ...
Booting Device: api19_0
Waiting 30 seconds

Traceback (most recent call last):
  File "main.py", line 380, in <module>
    main(app_dir)
  File "main.py", line 282, in main
    emulator.prepare_motifcore()
  File ".../sapienz/devices/emulator.py", line 97, in prepare_motifcore
    for device in get_devices():
  File ".../sapienz/devices/emulator.py", line 63, in get_devices
    assert len(ret) > 0
AssertionError

=================

I'd like to know if anyone had the same error and if anyone know how do I overcome this problem.

Thanks.

**Comment by makhshari** [comment]
You can solve it by running an emulator(or a real device) in parallel. Note that the android version on the running device should be 4.4 (KitKat). Google documentation for running the emulator in terminal: https://developer.android.com/studio/run/emulator-commandline
